rmorgan323/spirit-frontend

src/components/ConcernRow/ConcernRow.css
src/components/ConcernRow/ConcernRow.js
src/components/ConcernRow/ConcernRow.scss
src/reducers/index.js
src/reducers/patientConcerns.js
src/reducers/user.js

Add functionality to patient dashboard
Get values from inputs and send to store
Add Concerns component
Add ConcernsRow component
Add basic styling

Patient dashboard

---

src/components/Definition/Definition.css
src/components/Definition/Definition.js
src/components/Definition/Definition.scss

Get definitions from backend db
Pass definitions to store
Display filtered definitions on icon click in sliders

add definitions to sliders

---

src/components/ConcernRow/ConcernRow.css
src/components/ConcernRow/ConcernRow.js
src/components/ConcernRow/ConcernRow.scss
src/components/PatientCard/PatientCard.css
src/components/PatientCard/PatientCard.js
src/components/PatientCard/PatientCard.scss
src/components/PatientList/PatientList.css
src/components/PatientList/PatientList.js
src/components/PatientList/PatientList.scss
src/containers/PatientDashboard/PatientDashboard.css
src/containers/PatientDashboard/PatientDashboard.scss
src/containers/UserDashboard/UserDashboard.css
src/containers/UserDashboard/UserDashboard.js
src/containers/UserDashboard/UserDashboard.scss
src/variables.scss

Update styling on user dashboard page
Update styling on UserList component
Finish styling and code on ConcernRow component

update user dashboard page and styling

---

src/components/PatientHeader/PatientHeader.css
src/components/PatientHeader/PatientHeader.js
src/components/PatientHeader/PatientHeader.scss
src/containers/PatientDashboard/PatientDashboard.js
src/containers/Routes/Routes.js

add patient header with styling

---

src/actions/index.js
src/components/ConcernHeader/ConcernHeader.css
src/components/ConcernHeader/ConcernHeader.js
src/components/ConcernHeader/ConcernHeader.scss
src/containers/Routes/Routes.js

Add concern header with styling

add concern header

---

src/containers/Routes/Routes.js

Fix routes to render patientheader and concern header at the appropriate times

fix routes for patient and concern headers

---

src/actions/index.js
src/containers/Sessions/Sessions.js
src/helpers/postProcess/postProcess.js

- Build `renderedSessions` in `Sessions` component
- Call `createSessions` action in `Sessions`
- Mock out `createSessions` action in `actoins/index.js`
- Pull `selectedConcern` into `Sessions` component for use of `selectedConcern.id` with POST of session, process, therapy goal, and treatment plan

Sessions component

---

src/containers/BodyDiagram/BodyDiagram.js
src/reducers/patientSliders.js

Update and combine reducers for sliders component to work with larger datasets like the BodyDiagram component

update and combine sliders reducers

---

src/actions/index.js
src/containers/Sessions/Sessions.js
src/helpers/loadProcessBySession/loadProcessBySession.js
src/helpers/loadTherapyGoalBySession/loadTherapyGoalBySession.js
src/helpers/loadTreatmentPlanBySession/loadTreatmentPlanBySession.js
src/helpers/postSession/postSession.js
src/helpers/postTherapyGoal/postTherapyGoal.js
src/helpers/postTreatmentPlan/postTreatmentPlan.js
src/reducers/index.js
src/reducers/selectedProcess.js
src/reducers/selectedSession.js
src/reducers/selectedTherapyGoal.js
src/reducers/selectedTreatmentPlan.js

- Build `postTherapyGoal`, `postTreatmentPlan`, `loadTherapyGoalBySession`, and `loadTreatmentPlanBySession` helper files
- Complete `createSession` and `getSession` actions
- Call `createSession` in `Sessions` component to create new session and repopulate sessions
- Call `getSession` in `Sessions` component to select session and populate store with `selectedSession`, `selectedProcess`, `selectedTherapyGoal`, and `selectedTreatmentPlan`
- Build reducers for above store items

Session complete

---

src/components/ConcernHeader/ConcernHeader.css
src/components/ConcernHeader/ConcernHeader.js
src/components/ConcernHeader/ConcernHeader.scss
src/components/PatientHeader/PatientHeader.css
src/components/PatientHeader/PatientHeader.js
src/components/PatientHeader/PatientHeader.scss
src/components/SessionTabs/SessionTabs.css
src/components/SessionTabs/SessionTabs.js
src/components/SessionTabs/SessionTabs.scss
src/components/YesNoQuestions/YesNoQuestions.css
src/components/YesNoQuestions/YesNoQuestions.scss
src/containers/Header/Header.css
src/containers/Header/Header.scss
src/containers/Modulation/Modulation.js
src/containers/Postural/Postural.js

Clean up  and simplify styling for sessions component and headers that go inside sessions

styling for sessions

---

src/components/SessionTabs/SessionTabs.css
src/components/SessionTabs/SessionTabs.js
src/components/SessionTabs/SessionTabs.scss
src/containers/Sam/Sam.css
src/containers/Sam/Sam.js
src/containers/Sam/Sam.scss

Pivot sam page to be used inside of session
Import sam image to be used
Make sam image clickable to take user to different domains
Clean up styling on domains header

add sam page with clickable links

---

src/actions/index.js
src/containers/Executive/Executive.js
src/containers/PatientDashboard/PatientDashboard.js
src/containers/Social/Social.js

- Cleans up `actions/index.js`
- Fixes issues with newly added concern not migrating to store
- Fixes typos for `databaseName` in `Social` and `Executive` components

Error cleanup

---

src/actions/index.js
src/helpers/updateTreatmentPlan/updateTreatmentPlan.js
src/reducers/selectedTreatmentPlan.js

- Builds `updateTreatmentPlan` helper for PUT request to BE
- Builds `getTreatmentPlan` and `updatedTreatmentPlanToStore` to send updated values to store
- Adds `UPDATE_TREATMENT_PLAN` case to `selectedTreatmentPlan` reducer

Tx plan helpers

---

src/containers/Finish/Finish.js
src/containers/TreatmentPlanModule/TreatmentPlanModule.css
src/containers/TreatmentPlanModule/TreatmentPlanModule.js
src/containers/TreatmentPlanModule/TreatmentPlanModule.scss
src/containers/TreatmentPlans/TreatmentPlans.css
src/containers/TreatmentPlans/TreatmentPlans.js
src/containers/TreatmentPlans/TreatmentPlans.scss

Add TreatmentPlans component
Add TreatmentPlansModule component
Create tabs for entering treatment plans
Connect to action creators

add treatment plans component and styling

---

src/actions/index.js
src/containers/TreatmentPlanModule/TreatmentPlanModule.css
src/containers/TreatmentPlanModule/TreatmentPlanModule.js
src/containers/TreatmentPlanModule/TreatmentPlanModule.scss
src/helpers/updateTreatmentPlan/updateTreatmentPlan.js
src/reducers/selectedTreatmentPlan.js

Complete treatment plans functionality
Connect treatment plans to backend using thunk in actions
Connect treatment plans changes and updates to store
Complete styling for treatment plans

complete treatment plans functionality

---

src/containers/Finish/Finish.js
src/containers/TherapyGoals/TherapyGoals.css
src/containers/TherapyGoals/TherapyGoals.js
src/containers/TherapyGoals/TherapyGoals.scss

Add TherapyGoals component
Use sliders to create values
Call updateTherapyGoal on mouseleave of each category
Add styling for TherapyGoals

add therapy goals component with styling

---

src/actions/index.js
src/helpers/updateTherapyGoal/updateTherapyGoal.js
src/reducers/selectedTherapyGoal.js

- Builds `updateTherapyGoal` fetch helper file
- Builds `getTHerapyGoal` and `updatedTherapyGoalToStore` actions
- Adds `UPDATE_THERAPY_GOAL` case to `selectedTherapyGoal` reducer

Therapy goals helpers

---

src/actions/index.js
src/containers/TherapyGoals/TherapyGoals.js

Connect TherapyGoals component to store and backend
Use componentDidMount to display existing therapy goals

connect therapy goals component to backend and store

---

src/components/App/App.js
src/components/Definition/Definition.js
src/components/PatientCard/PatientCard.js
src/components/PatientHeader/PatientHeader.js
src/containers/Header/Header.js
src/containers/PatientDashboard/PatientDashboard.js
src/containers/Sam/Sam.js
src/containers/SessionHeader/SessionHeader.js
src/containers/SliderTen/SliderTen.js
src/containers/TreatmentPlans/TreatmentPlans.js
src/containers/Users/Users.js

Cleanup several console warnings

cleanup console warnings

---

src/actions/index.js
src/components/Finish/Finish.css
src/components/Finish/Finish.js
src/components/Finish/Finish.scss
src/helpers/updateSessionStatus/updateSessionStatus.js
src/reducers/selectedSession.js

Add button to complete session at end of Finish component
Update session status in backend
Update session status in store
Add button styling

add complete session functionality

---

src/actions/index.js
src/components/Finish/Finish.css
src/components/Finish/Finish.js
src/components/Finish/Finish.scss
src/containers/Sessions/Sessions.js
src/helpers/updateSessionStatus/updateSessionStatus.js
src/reducers/selectedSession.js

Add checkboxes to Sessions components on sessions that have been completed
Make sessions toggleable
Keep toggled checkbox indexes in array in state

Sessions checkboxes

---

src/actions/index.js
src/components/Finish/Finish.css
src/components/Finish/Finish.js
src/components/Finish/Finish.scss
src/containers/Sessions/Sessions.js
src/helpers/loadSessionsForComparison/loadSessionsForComparison.js
src/helpers/processSessionGoals/processSessionGoals.js
src/helpers/updateSessionStatus/updateSessionStatus.js
src/reducers/comparisonData.js
src/reducers/index.js
src/reducers/selectedSession.js

Create request for comparison data
Pull comparison data
Build helper function for formatting large datasets
Add comparison data to store on session comparison
Create actions and reducers for comparison data

Comparison data

---

src/actions/index.js
src/components/Finish/Finish.js
src/reducers/selectedSession.js
src/reducers/sessions.js

Redirect to sessions on completion of session
Send value of completed into session and selected session objects in store for immediate update

redirect back to sessions upon completed session

---

src/actions/index.js
src/containers/SessionTabs/SessionTabs.js
src/helpers/loadProcessesForComparison/loadProcessesForComparison.js
src/helpers/processProcessesData/processProcessesData.js
src/helpers/processSessionGoals/processSessionGoals.js
src/reducers/index.js
src/reducers/processesData.js
src/variables.scss

Pull processes data for use in session comparison chart
Format in data cleaning function
Create actions and reducers to get data to store

pull processes data process and move to store

---

src/actions/index.js
src/components/ComparisonCard/ComparisonCard.css
src/components/ComparisonCard/ComparisonCard.js
src/components/ComparisonCard/ComparisonCard.scss
src/components/SessionsComparison/SessionsComparison.css
src/components/SessionsComparison/SessionsComparison.js
src/components/SessionsComparison/SessionsComparison.scss
src/containers/SessionTabs/SessionTabs.js
src/containers/Sessions/Sessions.css
src/containers/Sessions/Sessions.js
src/containers/Sessions/Sessions.scss
src/helpers/loadProcessesForComparison/loadProcessesForComparison.js
src/helpers/processProcessesData/processProcessesData.js
src/helpers/processSessionGoals/processSessionGoals.js
src/reducers/index.js
src/reducers/processesData.js
src/variables.scss

Add SessionsComparison component
Add ComparisonCard component
Add styling to organize on any size dataset

Sessions comparison

---

src/components/CategorySliders/CategorySliders.css
src/components/CategorySliders/CategorySliders.scss
src/components/Executive/Executive.css
src/components/Executive/Executive.scss
src/components/Modulation/Modulation.css
src/components/Modulation/Modulation.scss
src/components/Postural/Postural.css
src/components/Postural/Postural.scss
src/components/Sensory/Sensory.css
src/components/Sensory/Sensory.scss
src/components/SessionHeader/SessionHeader.css
src/components/SessionHeader/SessionHeader.js
src/components/SessionHeader/SessionHeader.scss
src/components/Social/Social.css
src/components/Social/Social.scss
src/components/YesNoQuestions/YesNoQuestions.css
src/components/YesNoQuestions/YesNoQuestions.scss
src/containers/BodyDiagram/BodyDiagram.css
src/containers/BodyDiagram/BodyDiagram.scss
src/containers/SessionTabs/SessionTabs.css
src/containers/SessionTabs/SessionTabs.scss
src/containers/Sessions/Sessions.css
src/containers/Sessions/Sessions.scss
src/containers/SliderTen/SliderTen.css
src/containers/SliderTen/SliderTen.js
src/containers/SliderTen/SliderTen.scss
src/containers/YesNo/YesNo.css
src/containers/YesNo/YesNo.scss
src/variables.scss

Styling for components contained in sessions
Add borders to slider components to be changed via logical connections
Add 7 shades of greens to variables file
Adjust greens where used

styling for domains

---

package-lock.json
package.json
src/components/CategorySliders/CategorySliders.js
src/components/Modulation/Modulation.js
src/components/Sensory/Sensory.js
src/containers/ConcernHeader/ConcernHeader.css
src/containers/ConcernHeader/ConcernHeader.js
src/containers/ConcernHeader/ConcernHeader.scss
src/containers/Definition/Definition.js
src/containers/SessionTabs/SessionTabs.css
src/containers/SessionTabs/SessionTabs.scss
src/containers/SliderTen/SliderTen.js

Improve definition display logic to display only one definition on exact match between display title and definition title
Stop displaying definition on click outside of slider component

Update definitions behavior

---

src/components/Spirit/Spirit.js
src/containers/Create/Create.js
src/containers/Finish/Finish.css
src/containers/Finish/Finish.js
src/containers/Finish/Finish.scss
src/containers/Finish/__snapshots__/Finish.test.js.snap
src/containers/Join/Join.js
src/containers/SessionTabs/SessionTabs.js
src/containers/Sessions/Sessions.css
src/containers/Sessions/Sessions.js
src/containers/Sessions/Sessions.scss
src/containers/Sessions/__snapshots__/Sessions.test.js.snap
src/containers/UserDashboard/UserDashboard.css
src/containers/UserDashboard/UserDashboard.js
src/containers/UserDashboard/UserDashboard.scss
src/containers/UserDashboard/UserDashboard.test.js
src/containers/UserDashboard/__snapshots__/UserDashboard.test.js.snap
src/containers/ViewSession/ViewSession.js
src/data/copyContent/createClinicCopy.js
src/data/copyContent/finishCopy.js
src/data/copyContent/joinClinicCopy.js
src/data/copyContent/landingCopy.js
src/data/copyContent/patientDashboardCopy.js
src/data/copyContent/userDashboardCopy.js
src/data/posturalConnections.js
src/helpers/apiRoot.js
src/variables.scss

- Builds `ViewSession` component to scroll to top on render
- Builds conditional rendering of current clinic info in `Create` component
- Clears inputs when adding new patient on `UserDashboard`
- Adds section headers to `UserDashboard`
- Conditionally renders 'Current Patients' if there are no patients in `UserDashboard`
- Builds 'Results` button in `Sessions` to link to `ViewSession` component
- Conditionally renders 'Results' and 'Select' buttons in `Sessions` if session is marked complete
- Adds copy content to `Finish` component below 'Treatment Plans' and 'Therapy Goals' headers
- Builds data directory for `copyContent` and several copy content data objects
- Updates `posturalConnections` data per client request
- Does not highlight `SessionTabs` if session has been marked completed

Design touchups

---

src/components/Sam/__snapshots__/Sam.test.js.snap
src/containers/Create/__snapshots__/Create.test.js.snap
src/containers/Join/__snapshots__/Join.test.js.snap
src/containers/UserDashboard/__snapshots__/UserDashboard.test.js.snap
src/containers/ViewSession/ViewSession.test.js
src/helpers/apiRoot.js

Update snapshots
Fix console error

Update snapshots 2
